### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by luzpaz** [Fabricatable-Machines/Humphrey2#3]
Would be great to know under what license you're releasing this under?

**Comment by JensDyvik** [comment]
Thank you for pointing out the missing license. I usually do CC Attribution Share-a-like for my open hardware projects. What are your thoughts on this license? Do you have any other suggestions?

**Comment by TrevorFSmith** [comment]
I generally use a CERN license as it's specifically for hardware and they appear to know what they're doing.
https://github.com/Transmutable/swan/blob/main/LICENSE.txt

**Comment by JensDyvik** [comment]
Thank you for the CERN license tip! I will study it and make a decision. I have gotten the impression that opinions are quite mixed when it comes to Creative Commons licenses. The most important to me with an open hardware license is to make it clear to people that they are welcome to modify the project and use it in commercial settings if desired.

**Comment by JensDyvik** [comment]
A Creative Commons Attribution-ShareAlike license has been added to the readme
